### ISSUE TITLE
dependency on enum34 causes issues on macOS with Python 3.6

### ISSUE THREAD

**Issue by wjwwood** [PyCQA/flake8-import-order#149]
After updating `flake8-import-order` and its dependencies I get tracebacks like this:

```
Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 544, in <module>
    main()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 530, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sysconfig.py", line 580, in get_config_vars
    import _osx_support
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_osx_support.py", line 4, in <module>
    import re
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
```

After looking around on the internet I found:

https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag

Which implies having `enum34` installed causes this problem.

This dependency was introduced in:

https://github.com/PyCQA/flake8-import-order/commit/c52371fd5314429895064135146ef80e7c36a07f#diff-2eeaed663bd0d25b7e608891384b7298R32 

So I uninstalled it, but then `enum34` causes import to fail:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/flake8/__main__.py", line 4, in <module>
    cli.main()
  File "/usr/local/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 384, in _run
    self.run_checks()
  File "/usr/local/lib/python3.6/site-packages/flake8/main/application.py", line 310, in run_checks
    self.file_checker_manager.run()
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 321, in run
    self.run_serial()
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 305, in run_serial
    checker.run_checks()
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 579, in run_checks
    self.run_ast_checks()
  File "/usr/local/lib/python3.6/site-packages/flake8/checker.py", line 493, in run_ast_checks
    for (line_number, offset, text, check) in runner:
  File "/usr/local/lib/python3.6/site-packages/flake8_import_order/flake8_linter.py", line 91, in run
    for error in self.check_order():
  File "/usr/local/lib/python3.6/site-packages/flake8_import_order/checker.py", line 58, in check_order
    style_cls = style_entry_point.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2407, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2430, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'enum34' distribution was not found and is required by the application
```

The other recommendation from SO is to depend on `enum-compat` which only installs `enum34` when necessary. So perhaps the solution is to just depend on that instead of `enum34`?

**Comment by pgjones** [comment]
What version of setuptools are you installing with? It looks as if the environment marker `python_version <= "2.7"` is being ignored, which looks to be the case if setuptools is pre 20.5 (or a problematic version).

**Comment by wjwwood** [comment]
That's a fair point, I guess for some reason I was implicitly reading that as only for Python2, but I agree that condition should work.

We're using the latest version released each time:

https://ci.ros2.org/view/nightly/job/nightly_osx_release/755/consoleFull#console-section-3

Which, for the failure in question is `38.5.1`. I'll check upstream in `setuptools` to see if this issue has been reported... In which case this might be able to be closed.

**Comment by wjwwood** [comment]
Maybe this issue? https://github.com/pypa/setuptools/issues/1072

**Comment by sigmavirus24** [comment]
@wjwwood how are you installing flake8-import-order?

**Comment by wjwwood** [comment]
@sigmavirus24 with this one-liner from our CI:

```
"/Users/osrf/jenkins/workspace/nightly_osx_release/venv/bin/python" -m pip install -U EmPy coverage flake8 flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes mock nose pep8 pydocstyle pyflakes pyparsing pytest pytest-cov pytest-runner pyyaml vcstool
```
-- from: https://ci.ros2.org/view/nightly/job/nightly_osx_release/755/consoleFull#console-section-3

**Comment by mmerickel** [comment]
This issue is a silly gotcha with wheels. The wheel package does not support that syntax for optional deps.. you need to specify the dependency as an extra instead. If you look at the built whl metadata it will not have the appropriate environment markers in it.

Example:

```
extras_require={
  ':python_version <= "2.7"': ['enum34'],
}
```

Issue: https://github.com/pypa/wheel/issues/181

Note they claim if you re-build the wheel with setuptools > 36.2.0 then this is no longer an issue but I have not tried myself... just had to use the workaround on a bunch of projects over the years.

**Comment by wjwwood** [comment]
@mmerickel thanks for the hint. So what's the action item here? does this package need to have it's wheel rebuilt? Who does that? I'm not terribly familiar with the infrastructure behind wheels. Is it possible to avoid using wheels in our setup and/or does that even makes sense to do?

Sorry for the extra questions, I know it's starting to get out of the scope of this repository, though a suggestion on how to proceed would be appreciated!

**Comment by mmerickel** [comment]
Yes, the wheel needs to be rebuilt using one of the two methods I mentioned. You can specify `flake8-import-order --no-binary` in your `requirements.txt` or look into some of the other ways to tell pip not to use wheels for that package.

**Comment by pgjones** [comment]
Ok, I've rebuilt 0.17 as 0.17.1 using the latest wheel and setuptools, I hope this will fix the issue here. @wjwwood could you confirm if it does.

@mmerickel thanks for the detailed solution.

**Comment by wjwwood** [comment]
I'll check, this job is running with `Downloading flake8_import_order-0.17.1-py2.py3-none-any.whl` already in the console output:

- [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3343)](https://ci.ros2.org/job/ci_osx/3343/)

I'll check the test results to see when it finishes.

**Comment by wjwwood** [comment]
Looks like the related issues are gone now, thanks!
